### PR TITLE
Sodiumoxide migration and future plans for this crate

### LINKED ISSUE #1: Deprecation notice
```
    Finished release [optimized] target(s) in 58.80s
warning: the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```

### PR DESCRIPTION
**Pull request by brainstorm**
Fixes #1, #2 and moves away from sodiumoxide/libsodium-sys completely (and towards [RustCrypto](https://github.com/RustCrypto/) crates). This change is motivated by sodiumoxide getting both deprecated and collecting CVEs: https://github.com/sodiumoxide/sodiumoxide ... which breaks a Crypt4GH spec requirement:

> [§ 5.1 "Threat Analysis"](https://samtools.github.io/hts-specs/crypt4gh.pdf#subsection.5.1): "(...) Software MUST be kept up to date for security patches".

A side benefit is that this PR gets rid of unsafe/C FFI.

All tests pass except `test_keys.rs`, which is [not critical for our current htsget-rs usecase](https://github.com/umccr/htsget-rs/tree/crypt4gh). In addition, we wanted to seek some feedback from maintainers @MrRobb and @silverdaz: would it be acceptable to replace the custom SSH key parsing logic and delegate it to maintained RustCrypto crates such as https://crates.io/crates/ssh-key?: EDIT: Merged this PR, will tackle that in a new PR now that we have repo access.

More broadly speaking, we'd like to introduce some API-breaking changes [on the public side](https://github.com/EGA-archive/crypt4gh-rust#usage-in-rust), to make the code easier and more idiomatic, not involving explicit buffer arguments for instance. 

Would it be possible for the current maintainers to grant us some access to crates.io so that we can publish as co-maintainers? Any other arrangement? Let's discuss!

/cc @mmalenic @ohofmann @AlexanderSenf

### CODE REVIEW

**Comment by ohofmann** [comment]
@MrRobb @silverdaz I suspect you are currently busy with the hackathon and a million other things but once you get back to crypt4gh-rust let us know how you'd like to proceed?

**Comment by silverdaz** [comment]
@ohofmann, and @brainstorm: What do you say you become a maintainer of that repo, and eventually also the rust crate?
(Roberto @MrRobb: I think you need to pass it on)

**Comment by brainstorm** [comment]
> @ohofmann, and @brainstorm: What do you say you become a maintainer of that repo, and eventually also the rust crate? (Roberto @MrRobb: I think you need to pass it on)

Yes please, happy to! Instead of Oliver, me and @mmalenic would be the maintainers, thank you Frédéric!

**Comment by MrRobb** [comment]
> @ohofmann, and @brainstorm: What do you say you become a maintainer of that repo, and eventually also the rust crate? (Roberto @MrRobb: I think you need to pass it on)

I have added you both (@brainstorm and @mmalenic) as owners of the Rust crate. I don't have permissions on this repo anymore, so I can't merge the PR. Thank you for your work.

**Comment by brainstorm** [comment]
Happy new year everyone! 🎉 

Thanks a ton @MrRobb for the crates.io invite! @silverdaz Any progress about this repo's access? We'd like to merge this PR but also introduce some release engineering CI/CD we use for htsget-rs (mainly `release-plz`) via Github Actions.

**Pull request merged**
